[package]
name = "G19"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio"] }
argon2 = "0.5"
uuid = { version = "1.0", features = ["v4"] }
vincenty-core = "1.0.0"
clap = { version = "4.6.6", features = ["derive"] }
sysinfo = { version = "0.33", default-features = false, features = ["system"] }
