[package]
name = "G19"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]

tokio = { version = "1", features = ["full"] }

# gestione WebSocket asincroni per Tokio
tokio-tungstenite = "0.26"

# SQLx configurato specificamente per SQLite
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "sqlite"
] }

# per la crittografia nell'autenticazione
argon2 = { version = "0.5.3", features = ["std"] }

# per gestire JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

